# -*- coding: utf-8 -*-
"""PalmerPenguinsM4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zBdjn8hOTR4cFe7UozpywFlPkQTCXTM5
"""

from re import S
import math
# PalmerPenguinsM4.py
# Sergio Sasso
# 9/20/2026
# Uses branches to explore Palmer Penguin statistics.

# constants representing the species and count
SP_CHINSTRAP = "Chinstrap"
SP_GENTOO = "Gentoo"
SP_ADELIE = "Adelie"

# constants representing the number of observations for each species
NUM_CHINSTRAP = 68
NUM_GENTOO = 123
NUM_ADELIE = 151

species_names = [
    SP_CHINSTRAP,
    SP_GENTOO,
    SP_ADELIE
]

species_counts = [
    NUM_CHINSTRAP,
    NUM_GENTOO,
    NUM_ADELIE
]

total_species = len(species_names)
total_penguins = sum(species_counts)

average_penguins = total_penguins / total_species

average_penguins_rounded_up = math.ceil(average_penguins)

chinstrap_percent = species_counts[0] / total_penguins * 100
gentoo_percent = species_counts[1] / total_penguins * 100
adelie_percent = species_counts[2] / total_penguins * 100

species_percentages = [
    chinstrap_percent,
    gentoo_percent,
    adelie_percent
]

largest_count = max(species_counts)
smallest_count = min(species_counts)

largest_index = species_counts.index(largest_count)
smallest_index = species_counts.index(smallest_count)

largest_species = species_names[largest_index]
smallest_species = species_names[smallest_index]



# output the species names with introductory text

print("Introducing the Palmer Penguines:")
print(f"\t{SP_CHINSTRAP}!")
print(f"\t{SP_GENTOO}!")
print(f"and last but not least...")
print(f"\t{SP_ADELIE}!")
print()
print(f"There are a total of {str(total_species)} penguin species in this dataset.")
print(f"There are a total of {str(total_penguins)} penguins in this dataset.")
print(f"The average number of penguins per species is {average_penguins:.1f}.")
print(f"The average rounded up is {str(average_penguins_rounded_up)}.")
print()
print(f"{species_names[0]}:{species_counts[0]}({chinstrap_percent:.2f}%)")
print(f"{species_names[1]}:{species_counts[1]}({gentoo_percent:.2f}%)")
print(f"{species_names[2]}:{species_counts[2]}({adelie_percent:.2f}%)")
print()
print(f"The species with the most observations is {largest_species} with {largest_count} penguins.")
print(f"The species with the fewest observations is {smallest_species} with {smallest_count} penguins.")

print("Explore a species:")
species_choice = input("Enter Chinstrap, Gentoo, or Adelie:")
if species_choice not in species_names:
  print(f"{species_choice} is not one of the species in this dataset.")
else:

  if species_choice == species_names[0]:
    selected_index = 0
  elif species_choice == species_names[1]:
    selected_index = 1
  else:
    selected_index = 2
  selected_species = species_names[selected_index]
  selected_count = species_counts[selected_index]
  selected_percent = species_percentages[selected_index]

  if selected_percent < 25:
    size_category = "small"
  elif selected_percent >= 25 and selected_percent < 40:
    size_category = "medium"
  else:
    size_category = "large"

  if selected_species == largest_species or selected_species == smallest_species:
    if selected_species == largest_species:
      position_discription = "largest"
    elif selected_species == smallest_species:
      position_discription = "smallest"
  else:
    position_discription = "middle-sized"

  average_position = "above" if selected_count > average_penguins else "below"

  print(f"{selected_species} has {selected_count} observations, representing {selected_percent:.2f}% of the dataset.")
  print(f"{selected_species} is classified as a {size_category} species group.")
  print(f"{selected_species} is the {position_discription} species group")
  print(f"Its observation count is {average_position} the dataset average of {average_penguins:.1f}.")

